/* GConfInterface.c generated by valac 0.14.0, the Vala compiler
 * generated from GConfInterface.vala, do not modify */

/*  */
/*  GConfInterface.vala*/
/*  */
/*  Author:*/
/*       Jonas Frei <freijon@gmail.com>*/
/* */
/*  Copyright (c) 2011 Jonas Frei*/
/* */
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/* */
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/* */
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gconf/gconf-client.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define TYPE_GCONF_INTERFACE (gconf_interface_get_type ())
#define GCONF_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GCONF_INTERFACE, GConfInterface))
#define GCONF_INTERFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GCONF_INTERFACE, GConfInterfaceClass))
#define IS_GCONF_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GCONF_INTERFACE))
#define IS_GCONF_INTERFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GCONF_INTERFACE))
#define GCONF_INTERFACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GCONF_INTERFACE, GConfInterfaceClass))

typedef struct _GConfInterface GConfInterface;
typedef struct _GConfInterfaceClass GConfInterfaceClass;
typedef struct _GConfInterfacePrivate GConfInterfacePrivate;

#define GCONF_INTERFACE_TYPE_KEY (gconf_interface_key_get_type ())
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecGConfInterface ParamSpecGConfInterface;

struct _GConfInterface {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GConfInterfacePrivate * priv;
};

struct _GConfInterfaceClass {
	GTypeClass parent_class;
	void (*finalize) (GConfInterface *self);
};

typedef enum  {
	GCONF_INTERFACE_KEY_CHECK_INTERVAL,
	GCONF_INTERFACE_KEY_UPDATE_TOOL,
	GCONF_INTERFACE_KEY_NOTIFY,
	GCONF_INTERFACE_KEY_MANAGER_POPUP,
	GCONF_INTERFACE_KEY_SHOW_PASSIVE_ICON,
	GCONF_INTERFACE_KEY_SHOW_NUMBER_OF_UPDATES
} GConfInterfaceKey;

struct _ParamSpecGConfInterface {
	GParamSpec parent_instance;
};


static gpointer gconf_interface_parent_class = NULL;

gpointer gconf_interface_ref (gpointer instance);
void gconf_interface_unref (gpointer instance);
GParamSpec* param_spec_gconf_interface (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_gconf_interface (GValue* value, gpointer v_object);
void value_take_gconf_interface (GValue* value, gpointer v_object);
gpointer value_get_gconf_interface (const GValue* value);
GType gconf_interface_get_type (void) G_GNUC_CONST;
enum  {
	GCONF_INTERFACE_DUMMY_PROPERTY
};
GType gconf_interface_key_get_type (void) G_GNUC_CONST;
#define GCONF_INTERFACE_GCONF_APP_PATH "/apps/indicator-updatemanager"
#define GCONF_INTERFACE_CHECK_INTERVAL GCONF_INTERFACE_GCONF_APP_PATH "/check_interval"
#define GCONF_INTERFACE_UPDATE_TOOL GCONF_INTERFACE_GCONF_APP_PATH "/tool"
#define GCONF_INTERFACE_NOTIFY GCONF_INTERFACE_GCONF_APP_PATH "/notification"
#define GCONF_INTERFACE_MANAGER_POPUP "/apps/update-notifier/auto_launch"
#define GCONF_INTERFACE_SHOW_PASSIVE_ICON GCONF_INTERFACE_GCONF_APP_PATH "/show_passive_icon"
#define GCONF_INTERFACE_SHOW_NUMBER_OF_UPDATES GCONF_INTERFACE_GCONF_APP_PATH "/show_number"
gboolean gconf_interface_get_bool (GConfInterfaceKey key);
gint gconf_interface_get_int (GConfInterfaceKey key);
void gconf_interface_set_bool (GConfInterfaceKey key, gboolean value);
void gconf_interface_set_int (GConfInterfaceKey key, gint value);
GConfInterface* gconf_interface_new (void);
GConfInterface* gconf_interface_construct (GType object_type);
static void gconf_interface_finalize (GConfInterface* obj);


GType gconf_interface_key_get_type (void) {
	static volatile gsize gconf_interface_key_type_id__volatile = 0;
	if (g_once_init_enter (&gconf_interface_key_type_id__volatile)) {
		static const GEnumValue values[] = {{GCONF_INTERFACE_KEY_CHECK_INTERVAL, "GCONF_INTERFACE_KEY_CHECK_INTERVAL", "check-interval"}, {GCONF_INTERFACE_KEY_UPDATE_TOOL, "GCONF_INTERFACE_KEY_UPDATE_TOOL", "update-tool"}, {GCONF_INTERFACE_KEY_NOTIFY, "GCONF_INTERFACE_KEY_NOTIFY", "notify"}, {GCONF_INTERFACE_KEY_MANAGER_POPUP, "GCONF_INTERFACE_KEY_MANAGER_POPUP", "manager-popup"}, {GCONF_INTERFACE_KEY_SHOW_PASSIVE_ICON, "GCONF_INTERFACE_KEY_SHOW_PASSIVE_ICON", "show-passive-icon"}, {GCONF_INTERFACE_KEY_SHOW_NUMBER_OF_UPDATES, "GCONF_INTERFACE_KEY_SHOW_NUMBER_OF_UPDATES", "show-number-of-updates"}, {0, NULL, NULL}};
		GType gconf_interface_key_type_id;
		gconf_interface_key_type_id = g_enum_register_static ("GConfInterfaceKey", values);
		g_once_init_leave (&gconf_interface_key_type_id__volatile, gconf_interface_key_type_id);
	}
	return gconf_interface_key_type_id__volatile;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gboolean gconf_interface_get_bool (GConfInterfaceKey key) {
	gboolean result = FALSE;
	GConfClient* _tmp0_ = NULL;
	GConfClient* _tmp1_;
	GConfClient* client;
	gboolean output;
	GConfInterfaceKey _tmp2_;
	GError * _inner_error_ = NULL;
	_tmp0_ = gconf_client_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	client = _tmp1_;
	output = TRUE;
	_tmp2_ = key;
	switch (_tmp2_) {
		case GCONF_INTERFACE_KEY_NOTIFY:
		{
			{
				GConfClient* _tmp3_;
				gboolean _tmp4_ = FALSE;
				gboolean _tmp5_;
				_tmp3_ = client;
				_tmp4_ = gconf_client_get_bool (_tmp3_, GCONF_INTERFACE_NOTIFY, &_inner_error_);
				_tmp5_ = _tmp4_;
				if (_inner_error_ != NULL) {
					goto __catch8_g_error;
				}
				output = _tmp5_;
			}
			goto __finally8;
			__catch8_g_error:
			{
				GError* e = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_g_error_free0 (e);
			}
			__finally8:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return FALSE;
			}
			break;
		}
		case GCONF_INTERFACE_KEY_MANAGER_POPUP:
		{
			{
				GConfClient* _tmp6_;
				gboolean _tmp7_ = FALSE;
				gboolean _tmp8_;
				_tmp6_ = client;
				_tmp7_ = gconf_client_get_bool (_tmp6_, GCONF_INTERFACE_MANAGER_POPUP, &_inner_error_);
				_tmp8_ = _tmp7_;
				if (_inner_error_ != NULL) {
					goto __catch9_g_error;
				}
				output = _tmp8_;
			}
			goto __finally9;
			__catch9_g_error:
			{
				GError* e = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_g_error_free0 (e);
			}
			__finally9:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return FALSE;
			}
			break;
		}
		case GCONF_INTERFACE_KEY_SHOW_PASSIVE_ICON:
		{
			{
				GConfClient* _tmp9_;
				gboolean _tmp10_ = FALSE;
				gboolean _tmp11_;
				_tmp9_ = client;
				_tmp10_ = gconf_client_get_bool (_tmp9_, GCONF_INTERFACE_SHOW_PASSIVE_ICON, &_inner_error_);
				_tmp11_ = _tmp10_;
				if (_inner_error_ != NULL) {
					goto __catch10_g_error;
				}
				output = _tmp11_;
			}
			goto __finally10;
			__catch10_g_error:
			{
				GError* e = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_g_error_free0 (e);
			}
			__finally10:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return FALSE;
			}
			break;
		}
		case GCONF_INTERFACE_KEY_SHOW_NUMBER_OF_UPDATES:
		{
			{
				GConfClient* _tmp12_;
				gboolean _tmp13_ = FALSE;
				gboolean _tmp14_;
				_tmp12_ = client;
				_tmp13_ = gconf_client_get_bool (_tmp12_, GCONF_INTERFACE_SHOW_NUMBER_OF_UPDATES, &_inner_error_);
				_tmp14_ = _tmp13_;
				if (_inner_error_ != NULL) {
					goto __catch11_g_error;
				}
				output = _tmp14_;
			}
			goto __finally11;
			__catch11_g_error:
			{
				GError* e = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_g_error_free0 (e);
			}
			__finally11:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return FALSE;
			}
			break;
		}
		default:
		break;
	}
	result = output;
	_g_object_unref0 (client);
	return result;
}


gint gconf_interface_get_int (GConfInterfaceKey key) {
	gint result = 0;
	GConfClient* _tmp0_ = NULL;
	GConfClient* _tmp1_;
	GConfClient* client;
	gint output;
	GConfInterfaceKey _tmp2_;
	GError * _inner_error_ = NULL;
	_tmp0_ = gconf_client_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	client = _tmp1_;
	output = 0;
	_tmp2_ = key;
	switch (_tmp2_) {
		case GCONF_INTERFACE_KEY_CHECK_INTERVAL:
		{
			output = 2 * 60;
			{
				GConfClient* _tmp3_;
				gint _tmp4_ = 0;
				gint _tmp5_;
				_tmp3_ = client;
				_tmp4_ = gconf_client_get_int (_tmp3_, GCONF_INTERFACE_CHECK_INTERVAL, &_inner_error_);
				_tmp5_ = _tmp4_;
				if (_inner_error_ != NULL) {
					goto __catch12_g_error;
				}
				output = _tmp5_;
			}
			goto __finally12;
			__catch12_g_error:
			{
				GError* e = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_g_error_free0 (e);
			}
			__finally12:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return 0;
			}
			break;
		}
		case GCONF_INTERFACE_KEY_UPDATE_TOOL:
		{
			output = 0;
			{
				GConfClient* _tmp6_;
				gint _tmp7_ = 0;
				gint _tmp8_;
				_tmp6_ = client;
				_tmp7_ = gconf_client_get_int (_tmp6_, GCONF_INTERFACE_UPDATE_TOOL, &_inner_error_);
				_tmp8_ = _tmp7_;
				if (_inner_error_ != NULL) {
					goto __catch13_g_error;
				}
				output = _tmp8_;
			}
			goto __finally13;
			__catch13_g_error:
			{
				GError* e = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_g_error_free0 (e);
			}
			__finally13:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return 0;
			}
			break;
		}
		default:
		break;
	}
	result = output;
	_g_object_unref0 (client);
	return result;
}


void gconf_interface_set_bool (GConfInterfaceKey key, gboolean value) {
	GConfClient* _tmp0_ = NULL;
	GConfClient* _tmp1_;
	GConfClient* client;
	GConfInterfaceKey _tmp2_;
	GError * _inner_error_ = NULL;
	_tmp0_ = gconf_client_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	client = _tmp1_;
	_tmp2_ = key;
	switch (_tmp2_) {
		case GCONF_INTERFACE_KEY_NOTIFY:
		{
			{
				GConfClient* _tmp3_;
				gboolean _tmp4_;
				_tmp3_ = client;
				_tmp4_ = value;
				gconf_client_set_bool (_tmp3_, GCONF_INTERFACE_NOTIFY, _tmp4_, &_inner_error_);
				if (_inner_error_ != NULL) {
					goto __catch14_g_error;
				}
			}
			goto __finally14;
			__catch14_g_error:
			{
				GError* e = NULL;
				FILE* _tmp5_;
				GError* _tmp6_;
				const gchar* _tmp7_;
				e = _inner_error_;
				_inner_error_ = NULL;
				_tmp5_ = stderr;
				_tmp6_ = e;
				_tmp7_ = _tmp6_->message;
				fprintf (_tmp5_, "Error: Failed to save setting \"NOTIFY\": %s\n", _tmp7_);
				_g_error_free0 (e);
			}
			__finally14:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			break;
		}
		case GCONF_INTERFACE_KEY_MANAGER_POPUP:
		{
			{
				GConfClient* _tmp8_;
				gboolean _tmp9_;
				_tmp8_ = client;
				_tmp9_ = value;
				gconf_client_set_bool (_tmp8_, GCONF_INTERFACE_MANAGER_POPUP, _tmp9_, &_inner_error_);
				if (_inner_error_ != NULL) {
					goto __catch15_g_error;
				}
			}
			goto __finally15;
			__catch15_g_error:
			{
				GError* e = NULL;
				FILE* _tmp10_;
				GError* _tmp11_;
				const gchar* _tmp12_;
				e = _inner_error_;
				_inner_error_ = NULL;
				_tmp10_ = stderr;
				_tmp11_ = e;
				_tmp12_ = _tmp11_->message;
				fprintf (_tmp10_, "Error: Failed to save setting \"MANAGER_POPUP\": %s\n", _tmp12_);
				_g_error_free0 (e);
			}
			__finally15:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			break;
		}
		case GCONF_INTERFACE_KEY_SHOW_PASSIVE_ICON:
		{
			{
				GConfClient* _tmp13_;
				gboolean _tmp14_;
				_tmp13_ = client;
				_tmp14_ = value;
				gconf_client_set_bool (_tmp13_, GCONF_INTERFACE_SHOW_PASSIVE_ICON, _tmp14_, &_inner_error_);
				if (_inner_error_ != NULL) {
					goto __catch16_g_error;
				}
			}
			goto __finally16;
			__catch16_g_error:
			{
				GError* e = NULL;
				FILE* _tmp15_;
				GError* _tmp16_;
				const gchar* _tmp17_;
				e = _inner_error_;
				_inner_error_ = NULL;
				_tmp15_ = stderr;
				_tmp16_ = e;
				_tmp17_ = _tmp16_->message;
				fprintf (_tmp15_, "Error: Failed to save setting \"SHOW_PASSIVE_ICON\": %s\n", _tmp17_);
				_g_error_free0 (e);
			}
			__finally16:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			break;
		}
		case GCONF_INTERFACE_KEY_SHOW_NUMBER_OF_UPDATES:
		{
			{
				GConfClient* _tmp18_;
				gboolean _tmp19_;
				_tmp18_ = client;
				_tmp19_ = value;
				gconf_client_set_bool (_tmp18_, GCONF_INTERFACE_SHOW_NUMBER_OF_UPDATES, _tmp19_, &_inner_error_);
				if (_inner_error_ != NULL) {
					goto __catch17_g_error;
				}
			}
			goto __finally17;
			__catch17_g_error:
			{
				GError* e = NULL;
				FILE* _tmp20_;
				GError* _tmp21_;
				const gchar* _tmp22_;
				e = _inner_error_;
				_inner_error_ = NULL;
				_tmp20_ = stderr;
				_tmp21_ = e;
				_tmp22_ = _tmp21_->message;
				fprintf (_tmp20_, "Error: Failed to save setting \"SHOW_NUMBER_OF_UPDATES\": %s\n", _tmp22_);
				_g_error_free0 (e);
			}
			__finally17:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			break;
		}
		default:
		break;
	}
	_g_object_unref0 (client);
}


void gconf_interface_set_int (GConfInterfaceKey key, gint value) {
	GConfClient* _tmp0_ = NULL;
	GConfClient* _tmp1_;
	GConfClient* client;
	GConfInterfaceKey _tmp2_;
	GError * _inner_error_ = NULL;
	_tmp0_ = gconf_client_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	client = _tmp1_;
	_tmp2_ = key;
	switch (_tmp2_) {
		case GCONF_INTERFACE_KEY_CHECK_INTERVAL:
		{
			{
				GConfClient* _tmp3_;
				gint _tmp4_;
				_tmp3_ = client;
				_tmp4_ = value;
				gconf_client_set_int (_tmp3_, GCONF_INTERFACE_CHECK_INTERVAL, _tmp4_, &_inner_error_);
				if (_inner_error_ != NULL) {
					goto __catch18_g_error;
				}
			}
			goto __finally18;
			__catch18_g_error:
			{
				GError* e = NULL;
				FILE* _tmp5_;
				GError* _tmp6_;
				const gchar* _tmp7_;
				e = _inner_error_;
				_inner_error_ = NULL;
				_tmp5_ = stderr;
				_tmp6_ = e;
				_tmp7_ = _tmp6_->message;
				fprintf (_tmp5_, "Error: Failed to save setting \"CHECK_INTERVAL\": %s\n", _tmp7_);
				_g_error_free0 (e);
			}
			__finally18:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			break;
		}
		case GCONF_INTERFACE_KEY_UPDATE_TOOL:
		{
			{
				GConfClient* _tmp8_;
				gint _tmp9_;
				_tmp8_ = client;
				_tmp9_ = value;
				gconf_client_set_int (_tmp8_, GCONF_INTERFACE_UPDATE_TOOL, _tmp9_, &_inner_error_);
				if (_inner_error_ != NULL) {
					goto __catch19_g_error;
				}
			}
			goto __finally19;
			__catch19_g_error:
			{
				GError* e = NULL;
				FILE* _tmp10_;
				GError* _tmp11_;
				const gchar* _tmp12_;
				e = _inner_error_;
				_inner_error_ = NULL;
				_tmp10_ = stderr;
				_tmp11_ = e;
				_tmp12_ = _tmp11_->message;
				fprintf (_tmp10_, "Error: Failed to save setting \"UPDATE_TOOL\": %s\n", _tmp12_);
				_g_error_free0 (e);
			}
			__finally19:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (client);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			break;
		}
		default:
		break;
	}
	_g_object_unref0 (client);
}


GConfInterface* gconf_interface_construct (GType object_type) {
	GConfInterface* self = NULL;
	self = (GConfInterface*) g_type_create_instance (object_type);
	return self;
}


GConfInterface* gconf_interface_new (void) {
	return gconf_interface_construct (TYPE_GCONF_INTERFACE);
}


static void value_gconf_interface_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_gconf_interface_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		gconf_interface_unref (value->data[0].v_pointer);
	}
}


static void value_gconf_interface_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gconf_interface_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_gconf_interface_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_gconf_interface_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GConfInterface* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gconf_interface_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_gconf_interface_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GConfInterface** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gconf_interface_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_gconf_interface (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecGConfInterface* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_GCONF_INTERFACE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_gconf_interface (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GCONF_INTERFACE), NULL);
	return value->data[0].v_pointer;
}


void value_set_gconf_interface (GValue* value, gpointer v_object) {
	GConfInterface* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GCONF_INTERFACE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_GCONF_INTERFACE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gconf_interface_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gconf_interface_unref (old);
	}
}


void value_take_gconf_interface (GValue* value, gpointer v_object) {
	GConfInterface* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_GCONF_INTERFACE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_GCONF_INTERFACE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gconf_interface_unref (old);
	}
}


static void gconf_interface_class_init (GConfInterfaceClass * klass) {
	gconf_interface_parent_class = g_type_class_peek_parent (klass);
	GCONF_INTERFACE_CLASS (klass)->finalize = gconf_interface_finalize;
}


static void gconf_interface_instance_init (GConfInterface * self) {
	self->ref_count = 1;
}


static void gconf_interface_finalize (GConfInterface* obj) {
	GConfInterface * self;
	self = GCONF_INTERFACE (obj);
}


GType gconf_interface_get_type (void) {
	static volatile gsize gconf_interface_type_id__volatile = 0;
	if (g_once_init_enter (&gconf_interface_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_gconf_interface_init, value_gconf_interface_free_value, value_gconf_interface_copy_value, value_gconf_interface_peek_pointer, "p", value_gconf_interface_collect_value, "p", value_gconf_interface_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GConfInterfaceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gconf_interface_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GConfInterface), 0, (GInstanceInitFunc) gconf_interface_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType gconf_interface_type_id;
		gconf_interface_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GConfInterface", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&gconf_interface_type_id__volatile, gconf_interface_type_id);
	}
	return gconf_interface_type_id__volatile;
}


gpointer gconf_interface_ref (gpointer instance) {
	GConfInterface* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void gconf_interface_unref (gpointer instance) {
	GConfInterface* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GCONF_INTERFACE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



