/* UpdateChecker.c generated by valac 0.14.0, the Vala compiler
 * generated from UpdateChecker.vala, do not modify */

/*  */
/*  UpdateChecker.vala*/
/*  */
/*  Author:*/
/*       Jonas Frei <freijon@gmail.com>*/
/* */
/*  Copyright (c) 2011 Jonas Frei*/
/* */
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/* */
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/* */
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define TYPE_UPDATE_CHECKER (update_checker_get_type ())
#define UPDATE_CHECKER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UPDATE_CHECKER, UpdateChecker))
#define UPDATE_CHECKER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_UPDATE_CHECKER, UpdateCheckerClass))
#define IS_UPDATE_CHECKER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UPDATE_CHECKER))
#define IS_UPDATE_CHECKER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_UPDATE_CHECKER))
#define UPDATE_CHECKER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_UPDATE_CHECKER, UpdateCheckerClass))

typedef struct _UpdateChecker UpdateChecker;
typedef struct _UpdateCheckerClass UpdateCheckerClass;
typedef struct _UpdateCheckerPrivate UpdateCheckerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ParamSpecUpdateChecker ParamSpecUpdateChecker;

struct _UpdateChecker {
	GTypeInstance parent_instance;
	volatile int ref_count;
	UpdateCheckerPrivate * priv;
};

struct _UpdateCheckerClass {
	GTypeClass parent_class;
	void (*finalize) (UpdateChecker *self);
};

struct _UpdateCheckerPrivate {
	gchar** old_list;
	gint old_list_length1;
	gint _old_list_size_;
	gint _update_interval;
	gint _count;
	gboolean _is_security_update;
};

struct _ParamSpecUpdateChecker {
	GParamSpec parent_instance;
};


static gpointer update_checker_parent_class = NULL;

gpointer update_checker_ref (gpointer instance);
void update_checker_unref (gpointer instance);
GParamSpec* param_spec_update_checker (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_update_checker (GValue* value, gpointer v_object);
void value_take_update_checker (GValue* value, gpointer v_object);
gpointer value_get_update_checker (const GValue* value);
GType update_checker_get_type (void) G_GNUC_CONST;
#define UPDATE_CHECKER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_UPDATE_CHECKER, UpdateCheckerPrivate))
enum  {
	UPDATE_CHECKER_DUMMY_PROPERTY
};
UpdateChecker* update_checker_new (gint update_interval);
UpdateChecker* update_checker_construct (GType object_type, gint update_interval);
void update_checker_set_update_interval (UpdateChecker* self, gint value);
void* update_checker_check_for_updates (UpdateChecker* self);
static gchar** _vala_array_dup1 (gchar** self, int length);
static void update_checker_set_count (UpdateChecker* self, gint value);
static gboolean update_checker_check_if_security_update (UpdateChecker* self);
static void update_checker_set_is_security_update (UpdateChecker* self, gboolean value);
gint update_checker_get_count (UpdateChecker* self);
gboolean update_checker_get_is_security_update (UpdateChecker* self);
static gchar** _vala_array_dup2 (gchar** self, int length);
gint update_checker_get_update_interval (UpdateChecker* self);
static void g_cclosure_user_marshal_VOID__BOXED_INT_INT_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void update_checker_finalize (UpdateChecker* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


UpdateChecker* update_checker_construct (GType object_type, gint update_interval) {
	UpdateChecker* self = NULL;
	gint _tmp0_;
	self = (UpdateChecker*) g_type_create_instance (object_type);
	_tmp0_ = update_interval;
	update_checker_set_update_interval (self, _tmp0_);
	return self;
}


UpdateChecker* update_checker_new (gint update_interval) {
	return update_checker_construct (TYPE_UPDATE_CHECKER, update_interval);
}


static gchar** _vala_array_dup1 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static gchar** _vala_array_dup2 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void* update_checker_check_for_updates (UpdateChecker* self) {
	void* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	while (TRUE) {
		gchar* _tmp0_;
		gchar* output;
		gchar** _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		gint __tmp9__size_ = 0;
		const gchar* _tmp10_;
		gint _tmp11_;
		gint _tmp12_;
		gchar** _tmp18_;
		gint _tmp18__length1;
		gchar** _tmp19_;
		gint _tmp19__length1;
		gchar** packages;
		gint packages_length1;
		gint _packages_size_;
		gchar** _tmp20_;
		gint _tmp20__length1;
		gboolean is_same;
		gchar** _tmp36_;
		gint _tmp36__length1;
		gchar** _tmp37_;
		gint _tmp37__length1;
		gchar** _tmp38_;
		gint _tmp38__length1;
		const gchar* _tmp39_;
		gchar** _tmp50_;
		gint _tmp50__length1;
		gchar** _tmp51_;
		gint _tmp51__length1;
		gint _tmp52_;
		_tmp0_ = g_strdup ("");
		output = _tmp0_;
		{
			gchar* _tmp1_ = NULL;
			gchar* _tmp2_ = NULL;
			const gchar* _tmp3_;
			gint _tmp4_;
			gint _tmp5_;
			g_spawn_command_line_sync ("/usr/lib/update-notifier/apt-check -p", &_tmp1_, &_tmp2_, NULL, &_inner_error_);
			_g_free0 (output);
			output = _tmp1_;
			_g_free0 (output);
			output = _tmp2_;
			if (_inner_error_ != NULL) {
				goto __catch22_g_error;
			}
			_tmp3_ = output;
			_tmp4_ = strlen (_tmp3_);
			_tmp5_ = _tmp4_;
			if (_tmp5_ > 0) {
				const gchar* _tmp6_;
				gchar* _tmp7_;
				_tmp6_ = output;
				_tmp7_ = g_strconcat (_tmp6_, "\n", NULL);
				_g_free0 (output);
				output = _tmp7_;
			}
		}
		goto __finally22;
		__catch22_g_error:
		{
			GError* e = NULL;
			FILE* _tmp8_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp8_ = stderr;
			fprintf (_tmp8_, "Failed to check for updates.\n" \
"--> is \"update-notifier\" installed correctly on your system?\n");
			_g_error_free0 (e);
		}
		__finally22:
		if (_inner_error_ != NULL) {
			_g_free0 (output);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp10_ = output;
		_tmp11_ = strlen (_tmp10_);
		_tmp12_ = _tmp11_;
		if (_tmp12_ > 0) {
			const gchar* _tmp13_;
			gchar** _tmp14_;
			gchar** _tmp15_ = NULL;
			_tmp13_ = output;
			_tmp15_ = _tmp14_ = g_strsplit (_tmp13_, "\n", 0);
			_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) g_free), NULL);
			_tmp9_ = _tmp15_;
			_tmp9__length1 = _vala_array_length (_tmp14_);
			__tmp9__size_ = _tmp9__length1;
		} else {
			gchar* _tmp16_;
			gchar** _tmp17_ = NULL;
			_tmp16_ = g_strdup ("No updates");
			_tmp17_ = g_new0 (gchar*, 1 + 1);
			_tmp17_[0] = _tmp16_;
			_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) g_free), NULL);
			_tmp9_ = _tmp17_;
			_tmp9__length1 = 1;
			__tmp9__size_ = _tmp9__length1;
		}
		_tmp18_ = _tmp9_;
		_tmp18__length1 = _tmp9__length1;
		_tmp19_ = (_tmp18_ != NULL) ? _vala_array_dup1 (_tmp18_, _tmp18__length1) : ((gpointer) _tmp18_);
		_tmp19__length1 = _tmp18__length1;
		packages = _tmp19_;
		packages_length1 = _tmp19__length1;
		_packages_size_ = packages_length1;
		_tmp20_ = packages;
		_tmp20__length1 = packages_length1;
		if (_tmp20__length1 > 0) {
			gchar** _tmp21_;
			gint _tmp21__length1;
			const gchar* _tmp22_;
			_tmp21_ = packages;
			_tmp21__length1 = packages_length1;
			_tmp22_ = _tmp21_[0];
			if (g_strcmp0 (_tmp22_, "No updates") != 0) {
				gchar** _tmp23_;
				gint _tmp23__length1;
				gint _tmp24_ = 0;
				_tmp23_ = packages;
				_tmp23__length1 = packages_length1;
				_tmp24_ = _tmp23__length1 - 1;
				packages = g_renew (gchar*, packages, _tmp23__length1 - 1);
				(_tmp24_ > packages_length1) ? memset (packages + packages_length1, 0, sizeof (gchar*) * (_tmp24_ - packages_length1)) : NULL;
				packages_length1 = _tmp24_;
				_packages_size_ = _tmp24_;
			}
		}
		is_same = TRUE;
		{
			gint i;
			i = 0;
			{
				gboolean _tmp25_;
				_tmp25_ = TRUE;
				while (TRUE) {
					gboolean _tmp26_;
					gint _tmp28_;
					gchar** _tmp29_;
					gint _tmp29__length1;
					gchar** _tmp30_;
					gint _tmp30__length1;
					gint _tmp31_;
					const gchar* _tmp32_;
					gchar** _tmp33_;
					gint _tmp33__length1;
					gint _tmp34_;
					const gchar* _tmp35_;
					_tmp26_ = _tmp25_;
					if (!_tmp26_) {
						gint _tmp27_;
						_tmp27_ = i;
						i = _tmp27_ + 1;
					}
					_tmp25_ = FALSE;
					_tmp28_ = i;
					_tmp29_ = packages;
					_tmp29__length1 = packages_length1;
					if (!(_tmp28_ < _tmp29__length1)) {
						break;
					}
					_tmp30_ = packages;
					_tmp30__length1 = packages_length1;
					_tmp31_ = i;
					_tmp32_ = _tmp30_[_tmp31_];
					_tmp33_ = self->priv->old_list;
					_tmp33__length1 = self->priv->old_list_length1;
					_tmp34_ = i;
					_tmp35_ = _tmp33_[_tmp34_];
					if (g_strcmp0 (_tmp32_, _tmp35_) != 0) {
						is_same = FALSE;
						break;
					}
				}
			}
		}
		_tmp36_ = packages;
		_tmp36__length1 = packages_length1;
		_tmp37_ = self->priv->old_list;
		_tmp37__length1 = self->priv->old_list_length1;
		if (_tmp36__length1 != _tmp37__length1) {
			is_same = FALSE;
		}
		_tmp38_ = packages;
		_tmp38__length1 = packages_length1;
		_tmp39_ = _tmp38_[0];
		if (g_strcmp0 (_tmp39_, "No updates") != 0) {
			gboolean _tmp40_;
			_tmp40_ = is_same;
			if (!_tmp40_) {
				gchar** _tmp41_;
				gint _tmp41__length1;
				gboolean _tmp42_ = FALSE;
				gchar** _tmp43_;
				gint _tmp43__length1;
				gint _tmp44_;
				gboolean _tmp45_;
				_tmp41_ = packages;
				_tmp41__length1 = packages_length1;
				update_checker_set_count (self, _tmp41__length1);
				_tmp42_ = update_checker_check_if_security_update (self);
				update_checker_set_is_security_update (self, _tmp42_);
				_tmp43_ = packages;
				_tmp43__length1 = packages_length1;
				_tmp44_ = self->priv->_count;
				_tmp45_ = self->priv->_is_security_update;
				g_signal_emit_by_name (self, "update-event", _tmp43_, _tmp43__length1, _tmp44_, _tmp45_);
			}
		} else {
			gboolean _tmp46_;
			_tmp46_ = is_same;
			if (!_tmp46_) {
				gchar* _tmp47_;
				gchar** _tmp48_ = NULL;
				gchar** _tmp49_;
				gint _tmp49__length1;
				update_checker_set_count (self, 0);
				_tmp47_ = g_strdup ("No updates");
				_tmp48_ = g_new0 (gchar*, 1 + 1);
				_tmp48_[0] = _tmp47_;
				_tmp49_ = _tmp48_;
				_tmp49__length1 = 1;
				g_signal_emit_by_name (self, "update-event", _tmp49_, 1, 0, FALSE);
				_tmp49_ = (_vala_array_free (_tmp49_, _tmp49__length1, (GDestroyNotify) g_free), NULL);
			}
		}
		_tmp50_ = packages;
		_tmp50__length1 = packages_length1;
		_tmp51_ = (_tmp50_ != NULL) ? _vala_array_dup2 (_tmp50_, _tmp50__length1) : ((gpointer) _tmp50_);
		_tmp51__length1 = _tmp50__length1;
		self->priv->old_list = (_vala_array_free (self->priv->old_list, self->priv->old_list_length1, (GDestroyNotify) g_free), NULL);
		self->priv->old_list = _tmp51_;
		self->priv->old_list_length1 = _tmp51__length1;
		self->priv->_old_list_size_ = self->priv->old_list_length1;
		_tmp52_ = self->priv->_update_interval;
		g_usleep ((gulong) (_tmp52_ * 1000000));
		packages = (_vala_array_free (packages, packages_length1, (GDestroyNotify) g_free), NULL);
		_tmp9_ = (_vala_array_free (_tmp9_, _tmp9__length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (output);
	}
	return result;
}


static gboolean update_checker_check_if_security_update (UpdateChecker* self) {
	gboolean result = FALSE;
	gchar* _tmp0_;
	gchar* output;
	gint security_count;
	const gchar* _tmp3_;
	gchar** _tmp4_;
	gchar** _tmp5_ = NULL;
	gchar** _tmp6_;
	gint _tmp6__length1;
	const gchar* _tmp7_;
	gchar** _tmp8_;
	gchar** _tmp9_ = NULL;
	gchar** _tmp10_;
	gint _tmp10__length1;
	const gchar* _tmp11_;
	gint _tmp12_ = 0;
	gint _tmp13_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_strdup ("");
	output = _tmp0_;
	{
		gchar* _tmp1_ = NULL;
		g_spawn_command_line_sync ("/usr/lib/update-notifier/apt-check --human-readable", &_tmp1_, NULL, NULL, &_inner_error_);
		_g_free0 (output);
		output = _tmp1_;
		if (_inner_error_ != NULL) {
			goto __catch23_g_error;
		}
	}
	goto __finally23;
	__catch23_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stderr;
		fprintf (_tmp2_, "Failed to check if there are security updates.\n" \
"--> is \"update-notifier\" installed correctly on your system?\n");
		_g_error_free0 (e);
	}
	__finally23:
	if (_inner_error_ != NULL) {
		_g_free0 (output);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	security_count = 0;
	_tmp3_ = output;
	_tmp5_ = _tmp4_ = g_strsplit (_tmp3_, "\n", 0);
	_tmp6_ = _tmp5_;
	_tmp6__length1 = _vala_array_length (_tmp4_);
	_tmp7_ = _tmp6_[1];
	_tmp9_ = _tmp8_ = g_strsplit (_tmp7_, " ", 0);
	_tmp10_ = _tmp9_;
	_tmp10__length1 = _vala_array_length (_tmp8_);
	_tmp11_ = _tmp10_[0];
	_tmp12_ = atoi (_tmp11_);
	security_count = _tmp12_;
	_tmp10_ = (_vala_array_free (_tmp10_, _tmp10__length1, (GDestroyNotify) g_free), NULL);
	_tmp6_ = (_vala_array_free (_tmp6_, _tmp6__length1, (GDestroyNotify) g_free), NULL);
	_tmp13_ = security_count;
	if (_tmp13_ > 0) {
		result = TRUE;
		_g_free0 (output);
		return result;
	} else {
		result = FALSE;
		_g_free0 (output);
		return result;
	}
	_g_free0 (output);
}


gint update_checker_get_update_interval (UpdateChecker* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_update_interval;
	result = _tmp0_;
	return result;
}


void update_checker_set_update_interval (UpdateChecker* self, gint value) {
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_update_interval = _tmp0_;
}


gint update_checker_get_count (UpdateChecker* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_count;
	result = _tmp0_;
	return result;
}


static void update_checker_set_count (UpdateChecker* self, gint value) {
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_count = _tmp0_;
}


gboolean update_checker_get_is_security_update (UpdateChecker* self) {
	gboolean result;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_is_security_update;
	result = _tmp0_;
	return result;
}


static void update_checker_set_is_security_update (UpdateChecker* self, gboolean value) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_is_security_update = _tmp0_;
}


static void g_cclosure_user_marshal_VOID__BOXED_INT_INT_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__BOXED_INT_INT_BOOLEAN) (gpointer data1, gpointer arg_1, gint arg_2, gint arg_3, gboolean arg_4, gpointer data2);
	register GMarshalFunc_VOID__BOXED_INT_INT_BOOLEAN callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 5);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__BOXED_INT_INT_BOOLEAN) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_boxed (param_values + 1), g_value_get_int (param_values + 2), g_value_get_int (param_values + 3), g_value_get_boolean (param_values + 4), data2);
}


static void value_update_checker_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_update_checker_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		update_checker_unref (value->data[0].v_pointer);
	}
}


static void value_update_checker_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = update_checker_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_update_checker_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_update_checker_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		UpdateChecker* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = update_checker_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_update_checker_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	UpdateChecker** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = update_checker_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_update_checker (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecUpdateChecker* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_UPDATE_CHECKER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_update_checker (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UPDATE_CHECKER), NULL);
	return value->data[0].v_pointer;
}


void value_set_update_checker (GValue* value, gpointer v_object) {
	UpdateChecker* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UPDATE_CHECKER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UPDATE_CHECKER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		update_checker_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		update_checker_unref (old);
	}
}


void value_take_update_checker (GValue* value, gpointer v_object) {
	UpdateChecker* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UPDATE_CHECKER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UPDATE_CHECKER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		update_checker_unref (old);
	}
}


static void update_checker_class_init (UpdateCheckerClass * klass) {
	update_checker_parent_class = g_type_class_peek_parent (klass);
	UPDATE_CHECKER_CLASS (klass)->finalize = update_checker_finalize;
	g_type_class_add_private (klass, sizeof (UpdateCheckerPrivate));
	g_signal_new ("update_event", TYPE_UPDATE_CHECKER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT_INT_BOOLEAN, G_TYPE_NONE, 4, G_TYPE_STRV, G_TYPE_INT, G_TYPE_INT, G_TYPE_BOOLEAN);
}


static void update_checker_instance_init (UpdateChecker * self) {
	gchar* _tmp0_;
	gchar** _tmp1_ = NULL;
	self->priv = UPDATE_CHECKER_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("No updates");
	_tmp1_ = g_new0 (gchar*, 1 + 1);
	_tmp1_[0] = _tmp0_;
	self->priv->old_list = _tmp1_;
	self->priv->old_list_length1 = 1;
	self->priv->_old_list_size_ = self->priv->old_list_length1;
	self->priv->_update_interval = 2 * 60;
	self->priv->_count = 0;
	self->priv->_is_security_update = FALSE;
	self->ref_count = 1;
}


static void update_checker_finalize (UpdateChecker* obj) {
	UpdateChecker * self;
	self = UPDATE_CHECKER (obj);
	self->priv->old_list = (_vala_array_free (self->priv->old_list, self->priv->old_list_length1, (GDestroyNotify) g_free), NULL);
}


GType update_checker_get_type (void) {
	static volatile gsize update_checker_type_id__volatile = 0;
	if (g_once_init_enter (&update_checker_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_update_checker_init, value_update_checker_free_value, value_update_checker_copy_value, value_update_checker_peek_pointer, "p", value_update_checker_collect_value, "p", value_update_checker_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (UpdateCheckerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) update_checker_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UpdateChecker), 0, (GInstanceInitFunc) update_checker_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType update_checker_type_id;
		update_checker_type_id = g_type_register_fundamental (g_type_fundamental_next (), "UpdateChecker", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&update_checker_type_id__volatile, update_checker_type_id);
	}
	return update_checker_type_id__volatile;
}


gpointer update_checker_ref (gpointer instance) {
	UpdateChecker* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void update_checker_unref (gpointer instance) {
	UpdateChecker* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		UPDATE_CHECKER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



