/* UpdateChecker.c generated by valac 0.14.0, the Vala compiler
 * generated from UpdateChecker.vala, do not modify */

/*  */
/*  UpdateChecker.vala*/
/*  */
/*  Author:*/
/*       Jonas Frei <freijon@gmail.com>*/
/* */
/*  Copyright (c) 2011 Jonas Frei*/
/* */
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/* */
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/* */
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define TYPE_UPDATE_CHECKER (update_checker_get_type ())
#define UPDATE_CHECKER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UPDATE_CHECKER, UpdateChecker))
#define UPDATE_CHECKER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_UPDATE_CHECKER, UpdateCheckerClass))
#define IS_UPDATE_CHECKER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UPDATE_CHECKER))
#define IS_UPDATE_CHECKER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_UPDATE_CHECKER))
#define UPDATE_CHECKER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_UPDATE_CHECKER, UpdateCheckerClass))

typedef struct _UpdateChecker UpdateChecker;
typedef struct _UpdateCheckerClass UpdateCheckerClass;
typedef struct _UpdateCheckerPrivate UpdateCheckerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ParamSpecUpdateChecker ParamSpecUpdateChecker;

struct _UpdateChecker {
	GTypeInstance parent_instance;
	volatile int ref_count;
	UpdateCheckerPrivate * priv;
};

struct _UpdateCheckerClass {
	GTypeClass parent_class;
	void (*finalize) (UpdateChecker *self);
};

struct _UpdateCheckerPrivate {
	gint interval;
	gchar* package_list;
	gint package_count;
};

struct _ParamSpecUpdateChecker {
	GParamSpec parent_instance;
};


static gpointer update_checker_parent_class = NULL;

gpointer update_checker_ref (gpointer instance);
void update_checker_unref (gpointer instance);
GParamSpec* param_spec_update_checker (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_update_checker (GValue* value, gpointer v_object);
void value_take_update_checker (GValue* value, gpointer v_object);
gpointer value_get_update_checker (const GValue* value);
GType update_checker_get_type (void) G_GNUC_CONST;
#define UPDATE_CHECKER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_UPDATE_CHECKER, UpdateCheckerPrivate))
enum  {
	UPDATE_CHECKER_DUMMY_PROPERTY
};
UpdateChecker* update_checker_new (gint update_interval);
UpdateChecker* update_checker_construct (GType object_type, gint update_interval);
void* update_checker_check_for_updates (UpdateChecker* self);
void update_checker_set_count (UpdateChecker* self, gint value);
gint update_checker_get_update_interval (UpdateChecker* self);
void update_checker_set_update_interval (UpdateChecker* self, gint value);
gint update_checker_get_count (UpdateChecker* self);
static void g_cclosure_user_marshal_VOID__BOXED_INT_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void update_checker_finalize (UpdateChecker* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


UpdateChecker* update_checker_construct (GType object_type, gint update_interval) {
	UpdateChecker* self = NULL;
	gint _tmp0_;
	self = (UpdateChecker*) g_type_create_instance (object_type);
	_tmp0_ = update_interval;
	self->priv->interval = _tmp0_;
	return self;
}


UpdateChecker* update_checker_new (gint update_interval) {
	return update_checker_construct (TYPE_UPDATE_CHECKER, update_interval);
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


void* update_checker_check_for_updates (UpdateChecker* self) {
	void* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	while (TRUE) {
		gchar* _tmp0_;
		gchar* output;
		const gchar* _tmp3_;
		gchar** _tmp4_;
		gchar** _tmp5_ = NULL;
		gchar** output_lines;
		gint output_lines_length1;
		gint _output_lines_size_;
		gchar* _tmp6_;
		gchar* packages;
		gboolean look_for_packages;
		gchar** _tmp7_;
		gint _tmp7__length1;
		const gchar* _tmp19_;
		const gchar* _tmp20_;
		const gchar* _tmp34_;
		gchar* _tmp35_;
		gint _tmp36_;
		gint _tmp37_;
		_tmp0_ = g_strdup ("");
		output = _tmp0_;
		{
			gchar* _tmp1_ = NULL;
			g_spawn_command_line_sync ("apt-get upgrade -s", &_tmp1_, NULL, NULL, &_inner_error_);
			_g_free0 (output);
			output = _tmp1_;
			if (_inner_error_ != NULL) {
				goto __catch16_g_error;
			}
		}
		goto __finally16;
		__catch16_g_error:
		{
			GError* e = NULL;
			FILE* _tmp2_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp2_ = stderr;
			fprintf (_tmp2_, "Failed to check for updates.\n");
			_g_error_free0 (e);
		}
		__finally16:
		if (_inner_error_ != NULL) {
			_g_free0 (output);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp3_ = output;
		_tmp5_ = _tmp4_ = g_strsplit (_tmp3_, "\n", 0);
		output_lines = _tmp5_;
		output_lines_length1 = _vala_array_length (_tmp4_);
		_output_lines_size_ = output_lines_length1;
		_tmp6_ = g_strdup ("");
		packages = _tmp6_;
		look_for_packages = FALSE;
		_tmp7_ = output_lines;
		_tmp7__length1 = output_lines_length1;
		{
			gchar** line_collection = NULL;
			gint line_collection_length1 = 0;
			gint _line_collection_size_ = 0;
			gint line_it = 0;
			line_collection = _tmp7_;
			line_collection_length1 = _tmp7__length1;
			for (line_it = 0; line_it < _tmp7__length1; line_it = line_it + 1) {
				gchar* _tmp8_;
				gchar* line = NULL;
				_tmp8_ = g_strdup (line_collection[line_it]);
				line = _tmp8_;
				{
					const gchar* _tmp9_;
					gboolean _tmp10_ = FALSE;
					const gchar* _tmp11_;
					gboolean _tmp12_;
					_tmp9_ = line;
					_tmp10_ = string_contains (_tmp9_, "newly installed");
					if (_tmp10_) {
						_g_free0 (line);
						break;
					}
					_tmp11_ = line;
					if (g_strcmp0 (_tmp11_, "The following packages will be upgraded:") == 0) {
						look_for_packages = TRUE;
						_g_free0 (line);
						continue;
					}
					_tmp12_ = look_for_packages;
					if (_tmp12_) {
						const gchar* _tmp13_;
						const gchar* _tmp14_;
						const gchar* _tmp15_ = NULL;
						gchar* _tmp16_;
						gchar* _tmp17_;
						gchar* _tmp18_;
						_tmp13_ = packages;
						_tmp14_ = line;
						_tmp15_ = g_strchug (_tmp14_);
						_tmp16_ = g_strconcat (_tmp15_, " ", NULL);
						_tmp17_ = _tmp16_;
						_tmp18_ = g_strconcat (_tmp13_, _tmp17_, NULL);
						_g_free0 (packages);
						packages = _tmp18_;
						_g_free0 (_tmp17_);
					}
					_g_free0 (line);
				}
			}
		}
		_tmp19_ = packages;
		g_strchomp (_tmp19_);
		_tmp20_ = packages;
		if (g_strcmp0 (_tmp20_, "") != 0) {
			const gchar* _tmp21_;
			const gchar* _tmp22_;
			_tmp21_ = packages;
			_tmp22_ = self->priv->package_list;
			if (g_strcmp0 (_tmp21_, _tmp22_) != 0) {
				const gchar* _tmp23_;
				gchar** _tmp24_;
				gchar** _tmp25_ = NULL;
				gchar** update_list;
				gint update_list_length1;
				gint _update_list_size_;
				gchar** _tmp26_;
				gint _tmp26__length1;
				gchar** _tmp27_;
				gint _tmp27__length1;
				gchar** _tmp28_;
				gint _tmp28__length1;
				_tmp23_ = packages;
				_tmp25_ = _tmp24_ = g_strsplit (_tmp23_, " ", 0);
				update_list = _tmp25_;
				update_list_length1 = _vala_array_length (_tmp24_);
				_update_list_size_ = update_list_length1;
				_tmp26_ = update_list;
				_tmp26__length1 = update_list_length1;
				update_checker_set_count (self, _tmp26__length1);
				_tmp27_ = update_list;
				_tmp27__length1 = update_list_length1;
				_tmp28_ = update_list;
				_tmp28__length1 = update_list_length1;
				g_signal_emit_by_name (self, "update-event", _tmp27_, _tmp27__length1, _tmp28__length1);
				update_list = (_vala_array_free (update_list, update_list_length1, (GDestroyNotify) g_free), NULL);
			}
		} else {
			const gchar* _tmp29_;
			const gchar* _tmp30_;
			_tmp29_ = packages;
			_tmp30_ = self->priv->package_list;
			if (g_strcmp0 (_tmp29_, _tmp30_) != 0) {
				gchar* _tmp31_;
				gchar** _tmp32_ = NULL;
				gchar** _tmp33_;
				gint _tmp33__length1;
				update_checker_set_count (self, 0);
				_tmp31_ = g_strdup ("No updates");
				_tmp32_ = g_new0 (gchar*, 1 + 1);
				_tmp32_[0] = _tmp31_;
				_tmp33_ = _tmp32_;
				_tmp33__length1 = 1;
				g_signal_emit_by_name (self, "update-event", _tmp33_, 1, 0);
				_tmp33_ = (_vala_array_free (_tmp33_, _tmp33__length1, (GDestroyNotify) g_free), NULL);
			}
		}
		_tmp34_ = packages;
		_tmp35_ = g_strdup (_tmp34_);
		_g_free0 (self->priv->package_list);
		self->priv->package_list = _tmp35_;
		_tmp36_ = update_checker_get_update_interval (self);
		_tmp37_ = _tmp36_;
		g_usleep ((gulong) (_tmp37_ * 1000000));
		_g_free0 (packages);
		output_lines = (_vala_array_free (output_lines, output_lines_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (output);
	}
	return result;
}


gint update_checker_get_update_interval (UpdateChecker* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->interval;
	result = _tmp0_;
	return result;
}


void update_checker_set_update_interval (UpdateChecker* self, gint value) {
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->interval = _tmp0_;
}


gint update_checker_get_count (UpdateChecker* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->package_count;
	result = _tmp0_;
	return result;
}


void update_checker_set_count (UpdateChecker* self, gint value) {
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->package_count = _tmp0_;
}


static void g_cclosure_user_marshal_VOID__BOXED_INT_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__BOXED_INT_INT) (gpointer data1, gpointer arg_1, gint arg_2, gint arg_3, gpointer data2);
	register GMarshalFunc_VOID__BOXED_INT_INT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 4);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__BOXED_INT_INT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_boxed (param_values + 1), g_value_get_int (param_values + 2), g_value_get_int (param_values + 3), data2);
}


static void value_update_checker_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_update_checker_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		update_checker_unref (value->data[0].v_pointer);
	}
}


static void value_update_checker_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = update_checker_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_update_checker_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_update_checker_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		UpdateChecker* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = update_checker_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_update_checker_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	UpdateChecker** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = update_checker_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_update_checker (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecUpdateChecker* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_UPDATE_CHECKER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_update_checker (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UPDATE_CHECKER), NULL);
	return value->data[0].v_pointer;
}


void value_set_update_checker (GValue* value, gpointer v_object) {
	UpdateChecker* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UPDATE_CHECKER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UPDATE_CHECKER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		update_checker_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		update_checker_unref (old);
	}
}


void value_take_update_checker (GValue* value, gpointer v_object) {
	UpdateChecker* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_UPDATE_CHECKER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_UPDATE_CHECKER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		update_checker_unref (old);
	}
}


static void update_checker_class_init (UpdateCheckerClass * klass) {
	update_checker_parent_class = g_type_class_peek_parent (klass);
	UPDATE_CHECKER_CLASS (klass)->finalize = update_checker_finalize;
	g_type_class_add_private (klass, sizeof (UpdateCheckerPrivate));
	g_signal_new ("update_event", TYPE_UPDATE_CHECKER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOXED_INT_INT, G_TYPE_NONE, 3, G_TYPE_STRV, G_TYPE_INT, G_TYPE_INT);
}


static void update_checker_instance_init (UpdateChecker * self) {
	gchar* _tmp0_;
	self->priv = UPDATE_CHECKER_GET_PRIVATE (self);
	self->priv->interval = 2 * 60;
	_tmp0_ = g_strdup ("");
	self->priv->package_list = _tmp0_;
	self->priv->package_count = 0;
	self->ref_count = 1;
}


static void update_checker_finalize (UpdateChecker* obj) {
	UpdateChecker * self;
	self = UPDATE_CHECKER (obj);
	_g_free0 (self->priv->package_list);
}


GType update_checker_get_type (void) {
	static volatile gsize update_checker_type_id__volatile = 0;
	if (g_once_init_enter (&update_checker_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_update_checker_init, value_update_checker_free_value, value_update_checker_copy_value, value_update_checker_peek_pointer, "p", value_update_checker_collect_value, "p", value_update_checker_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (UpdateCheckerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) update_checker_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UpdateChecker), 0, (GInstanceInitFunc) update_checker_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType update_checker_type_id;
		update_checker_type_id = g_type_register_fundamental (g_type_fundamental_next (), "UpdateChecker", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&update_checker_type_id__volatile, update_checker_type_id);
	}
	return update_checker_type_id__volatile;
}


gpointer update_checker_ref (gpointer instance) {
	UpdateChecker* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void update_checker_unref (gpointer instance) {
	UpdateChecker* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		UPDATE_CHECKER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



